use bt1 ; 
-- 1 
select MASP, TENSP
FROM SANPHAM 
where nuocsx = 'trung quoc' ;
-- 2
select masp, tensp
from sanpham
where dvt in ('cay','quyen');
-- 3
select masp, tensp
from sanpham
where masp like 'B%01' ; 
-- 4
select masp, tensp
from sanpham
where nuocsx='trung quoc' and gia between 20 and 30;
-- 5
select masp, tensp 
from sanpham
where nuocsx in('trung quoc','thai lan') and gia between 20 and 30; 
-- 6
select sohd, trigia
from hoadon
where nghd in ('2007-01-01', '2007-01-02') ; 
-- 7
SELECT SOHD, TRIGIA 
FROM HOADON 
WHERE MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007 
ORDER BY NGHD ASC, TRIGIA DESC;
-- 8
SELECT DISTINCT KHACHHANG.MAKH, KHACHHANG.HOTEN 
FROM KHACHHANG 
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH 
WHERE HOADON.NGHD = '2007-01-01';
-- 9
SELECT DISTINCT SANPHAM.MASP, SANPHAM.TENSP 
FROM SANPHAM 
JOIN CTHD ON SANPHAM.MASP = CTHD.MASP 
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD 
JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH 
WHERE KHACHHANG.HOTEN = 'nguyen van a' 
  AND MONTH(HOADON.NGHD) = 10 
  AND YEAR(HOADON.NGHD) = 2006;
-- 10
SELECT HOADON.SOHD, HOADON.TRIGIA 
FROM HOADON 
JOIN NHANVIEN ON HOADON.MANV = NHANVIEN.MANV 
WHERE NHANVIEN.HOTEN = 'nguyen van b' 
  AND HOADON.NGHD = '2006-10-10';
-- 11
SELECT DISTINCT SOHD 
FROM CTHD 
WHERE MASP IN ('BB01', 'BB02');
-- 12
SELECT DISTINCT SOHD 
FROM CTHD 
WHERE MASP IN ('BB01', 'BB02') 
  AND SL BETWEEN 10 AND 20;
-- 13
SELECT SOHD 
FROM CTHD 
WHERE (MASP = 'BB01' AND SL BETWEEN 10 AND 20) 
   OR (MASP = 'BB02' AND SL BETWEEN 10 AND 20)
GROUP BY SOHD 
HAVING COUNT(DISTINCT MASP) = 2;
-- 14
SELECT DISTINCT SANPHAM.MASP, SANPHAM.TENSP 
FROM SANPHAM 
LEFT JOIN CTHD ON SANPHAM.MASP = CTHD.MASP 
LEFT JOIN HOADON ON CTHD.SOHD = HOADON.SOHD 
WHERE SANPHAM.NUOCSX = 'trung quoc' 
   OR HOADON.NGHD = '2007-01-01';
   
-- 15
SELECT MASP, TENSP 
FROM SANPHAM 
WHERE MASP NOT IN (SELECT DISTINCT MASP FROM CTHD);

-- 16
SELECT MASP, TENSP 
FROM SANPHAM 
WHERE MASP NOT IN (
    SELECT DISTINCT MASP 
    FROM CTHD 
    JOIN HOADON ON CTHD.SOHD = HOADON.SOHD 
    WHERE YEAR(NGHD) = 2006
);
-- 17
SELECT MASP, TENSP 
FROM SANPHAM 
WHERE NUOCSX = 'Trung Quốc' 
  AND MASP NOT IN (
      SELECT DISTINCT MASP 
      FROM CTHD 
      JOIN HOADON ON CTHD.SOHD = HOADON.SOHD 
      WHERE YEAR(NGHD) = 2006
  );

-- 18
SELECT COUNT(*) AS SoHoaDon 
FROM HOADON 
JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH 
WHERE KHACHHANG.NGDK IS NULL;

-- 19
SELECT MAX(TRIGIA) AS CaoNhat, MIN(TRIGIA) AS ThapNhat 
FROM HOADON;

-- 20
SELECT AVG(TRIGIA) AS TriGiaTrungBinh 
FROM HOADON 
WHERE YEAR(NGHD) = 2006;

-- 21
SELECT SUM(TRIGIA) AS DoanhThu 
FROM HOADON 
WHERE YEAR(NGHD) = 2006;

-- 22
SELECT SOHD 
FROM HOADON 
WHERE YEAR(NGHD) = 2006 
  AND TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR(NGHD) = 2006);

-- 23
SELECT KHACHHANG.HOTEN 
FROM KHACHHANG 
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH 
WHERE YEAR(HOADON.NGHD) = 2006 
  AND HOADON.TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR(NGHD) = 2006);

-- 24
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, SUM(HOADON.TRIGIA) AS DoanhSo
FROM KHACHHANG 
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY DoanhSo DESC
LIMIT 3;

-- 25
SELECT MASP, TENSP 
FROM SANPHAM 
WHERE GIA IN (
    SELECT GIA 
    FROM SANPHAM 
    GROUP BY GIA 
    ORDER BY GIA DESC 
    LIMIT 3
);

-- 26
SELECT MASP, TENSP 
FROM SANPHAM 
WHERE NUOCSX = 'trung quoc' 
  AND GIA IN (
      SELECT GIA 
      FROM SANPHAM 
      GROUP BY GIA 
      ORDER BY GIA ASC 
      LIMIT 3
  );
  
-- 27
SELECT MASP, TENSP 
FROM SANPHAM 
WHERE NUOCSX = 'Trung Quốc' 
  AND GIA IN (
      SELECT GIA 
      FROM SANPHAM 
      WHERE NUOCSX = 'Trung Quốc' 
      GROUP BY GIA 
      ORDER BY GIA ASC 
      LIMIT 3
  );

-- 28
SET @rank = 0;
SELECT @rank := @rank + 1 AS XepHang, MAKH, HOTEN, DoanhSo
FROM (
    SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, SUM(HOADON.TRIGIA) AS DoanhSo
    FROM KHACHHANG 
    JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
    GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
    ORDER BY DoanhSo DESC
    LIMIT 3
) AS T;

-- 29
SELECT COUNT(*) AS TongSoSanPham
FROM SANPHAM
WHERE NUOCSX = 'Trung Quốc';

-- 30
SELECT NUOCSX, COUNT(*) AS TongSoSanPham
FROM SANPHAM
GROUP BY NUOCSX;

-- 31
SELECT NUOCSX, 
       MAX(GIA) AS GiaCaoNhat, 
       MIN(GIA) AS GiaThapNhat, 
       AVG(GIA) AS GiaTrungBinh
FROM SANPHAM
GROUP BY NUOCSX;

-- 32
SELECT NGHD, SUM(TRIGIA) AS DoanhThu
FROM HOADON
GROUP BY NGHD;

-- 33
SELECT CTHD.MASP, SUM(CTHD.SL) AS TongSoLuong
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE HOADON.NGHD = '2006-10-28'
GROUP BY CTHD.MASP;

-- 34
SELECT MONTH(NGHD) AS Thang, SUM(TRIGIA) AS DoanhThu
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD);

-- 35
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, COUNT(HOADON.SOHD) AS SoLanMua
FROM KHACHHANG 
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY SoLanMua DESC
LIMIT 1;

-- 36
SELECT CTHD.MASP, SANPHAM.TENSP, SUM(CTHD.SL) AS TongSoLuong
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE YEAR(HOADON.NGHD) = 2006
GROUP BY CTHD.MASP, SANPHAM.TENSP
ORDER BY TongSoLuong ASC
LIMIT 1;

-- 37
SELECT MONTH(NGHD) AS Thang, SUM(TRIGIA) AS DoanhThu
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY DoanhThu ASC
LIMIT 1;

-- 38
SELECT S1.NUOCSX, S1.MASP, S1.TENSP, S1.GIA
FROM SANPHAM S1
JOIN (
    SELECT NUOCSX, MAX(GIA) AS MaxGia
    FROM SANPHAM
    GROUP BY NUOCSX
) S2 ON S1.NUOCSX = S2.NUOCSX AND S1.GIA = S2.MaxGia;

-- 39
SELECT MAKH, HOTEN, COUNT(SOHD) AS SoLanMua
FROM (
    SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, HOADON.SOHD
    FROM KHACHHANG
    JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
    GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
    ORDER BY SUM(HOADON.TRIGIA) DESC
    LIMIT 10
) AS Top10
GROUP BY MAKH, HOTEN
ORDER BY SoLanMua DESC
LIMIT 1;

-- 40
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(*) >= 3;







